### PR TITLE
clean up edit event page

### PR DESCRIPTION
**Pull request by benyeom**
started off new layout for edit events page

### CODE REVIEW

**Review by LoganTown — CHANGES_REQUESTED** [review]
Can you add the add roles, and add invitees to the box in the middle instead of just squished to the side? Also is there a more clear word for add invitees? like, invites or something

**Review by Curtis-Barnhart — CHANGES_REQUESTED** [review]
can we maybe get a grey ish looking background so it looks similar to the create event one? Also can we make the text input box for description larger so that you can actually see a large description in it?

**Review by mnugent04 — CHANGES_REQUESTED** [review]
the text box in edit event under the event discription is super large

**Review by gyishak — CHANGES_REQUESTED** [review]
I feel like the way the headers for each box like "Basic Info" should be in the center and the part that says "Give your event a name and add any details to make it unique!" should be underneath it centered as well.

**Comment by Curtis-Barnhart** [comment]
> I feel like the way the headers for each box like "Basic Info" should be in the center and the part that says "Give your event a name and add any details to make it unique!" should be underneath it centered as well.

Should those be in the center? I feel like that would look worse. It'd be good to get everyone's opinion, but I think it's fine as is. I'm just gonna make one commit to make the text input boxes on new lines because right now only one is just so that they are consistent.

**Comment by Curtis-Barnhart** [comment]
Also to Meghan's comment... isn't that what we want? It's weird if the box is small when we allow for 200 or something characters to go in there.

**Comment by gyishak** [comment]
> > I feel like the way the headers for each box like "Basic Info" should be in the center and the part that says "Give your event a name and add any details to make it unique!" should be underneath it centered as well.
> 
> Should those be in the center? I feel like that would look worse. It'd be good to get everyone's opinion, but I think it's fine as is. I'm just gonna make one commit to make the text input boxes on new lines because right now only one is just so that they are consistent.

I am good with either it was just where the "Give your event a name and add any details to make it unique!" that had a bit of strange placement for me but I am good with either ways

**Review by Curtis-Barnhart — APPROVED** [review]
I byu

**Review by gyishak — APPROVED** [review]

**Pull request merged**
