### PR TITLE
navbar

### PR DESCRIPTION
**Pull request by benyeom**
added dropdown function for navbar

### CODE REVIEW

**Comment by Curtis-Barnhart** [comment]
Hang on I'm working on some syntactical changes no one merge this thing yet.

**Comment by Curtis-Barnhart** [comment]
Okay I buy it.

**Review by Curtis-Barnhart — DISMISSED** [review]

**Comment by Curtis-Barnhart** [comment]
Also if anyone is hesitant about the color scheme on the dashboard and it not matching the header, I've added a ticket to unify our color scheme because I think it makes more sense to consider that a separate task of its own. We are going to have a lot of prs coming in and we don't want to keep going back to change the color scheme of each one to match the others, and it seems like it would be easier if one person could just do all the colors in their own pr.

**Comment by benyeom** [comment]
for the new accounts page, it does work actually logging you out and saying "anonymous user" but the dropdown menu w/ dashboard/create event/logout is still there. what if we deleted that whole section from the navbar and just have a "back to login" button?

**Comment by mnugent04** [comment]
when creating an event with a description of 200 characters the format gets weird

**Review by mnugent04 — COMMENTED** [review]
when creating an event with a description of 200 characters the format gets wacky

**Review by Curtis-Barnhart — APPROVED** [review]

**Review by gyishak — APPROVED** [review]

**Pull request merged**
